version: '2'

services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: '{{ vault_db_admin_user }}'
      POSTGRES_PASSWORD: '{{ vault_db_admin_password }}'
    volumes:
      - pg-data:/var/lib/postgresql/db-data
    ports:
      - '5432:5432'
    restart: always

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    restart: always

volumes:
  pg-data:
