---
- name: Create app user
  community.postgresql.postgresql_user:
    name: '{{ app.value.db.user }}'
    password: '{{ app.value.db.password }}'
    ssl_mode: disable  # single host; no need

- name: Create database
  community.postgresql.postgresql_db:
    name: '{{ app.value.db.name }}'
    owner: '{{ app.value.db.user }}'
    ssl_mode: disable  # single host; no need

- name: Add database extensions
  community.postgresql.postgresql_ext:
    name: '{{ item }}'
    db: '{{ app.value.db.name }}'
  loop: '{{ app.value.db.extensions }}'
