---
- name: Update and ugrade APT cache to the lastest packages
  apt:
    upgrade: dist
    cache_valid_time: 3600

#- name: Set up Postgres
#  include_tasks: roles/common/tasks/postgres.yml

#- name: Set up Redis
#  include_tasks: roles/common/tasks/redis.yml

- name: Set up Docker & Compose
  include_tasks: roles/common/tasks/docker.yml

- name: Set up shared Docker Compose resources
  include_tasks: roles/api_trezcool/tasks/shared_compose_resources.yml

- name: Set up Caddy
  include_role:
    name: caddy_ansible.caddy_ansible
  vars:
    caddy_packages: [ "github.com/caddy-dns/route53" ]
    caddy_environment_variables:
      AWS_ACCESS_KEY_ID: '{{ aws_access_key_id }}'
      AWS_SECRET_ACCESS_KEY: '{{ aws_secret_access_key }}'
      AWS_REGION: '{{ aws_region }}'
    caddy_config: "{{ lookup('template', 'files/Caddyfile.j2') }}"
    caddy_systemd_capabilities_enabled: yes
