---
- name: Install PostgreSQL
  apt:
    pkg:
      - postgresql
      - postgresql-contrib

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Install psycopg2
  pip:
    name:
      - psycopg2-binary
    state: latest

- name: Set up Postgres users and databases
  become_user: postgres
  block:
    - name: Create admin user
      community.postgresql.postgresql_user:
        name: '{{ db_admin_user }}'
        password: '{{ db_admin_password }}'
        ssl_mode: disable  # single host; no need

    - name: Set up apps DBs
      include_tasks: roles/common/tasks/_pg_app_db.yml
      loop: '{{ apps | dict2items }}'
      loop_control:
        loop_var: app
      when: app.value.db.engine == "postgres"
